language: node_js

jobs:
  include:
    - stage: test
      env:
        - NODE_ENV=development
      node_js: lts/*
      script:
        - npm t
        - npm run check-coverage
    - stage: release
      env:
        - NODE_ENV=development
      node_js: lts/*
      script:
        - npm run semantic-release
